### ISSUE TITLE
Preprocessing

### ISSUE THREAD

**Issue by tiimoS** [literally-a-placeholder/exercise2#1]

**Comment by tiimoS** [comment]
Crop, Binarization, Resize

**Comment by timogi** [comment]
es git iz es file "crop.py" wo dür aui biuder düregeit, d wörter useschnitt u se uf 100x100 skaliert. Evtl muess me d bilder no chly bearbeite wüu ds blatt isch ja ni ganz wiis, resp. dr text ni ganz schwarz. 

#apply image correction here 
isch wahrschiinlech dr best ort für das wüu nachem skalliere si'd kantene ja nümm so gnau

(dr output folder hani extra ni ufeglade wüu di files wärde ja de no optimiert aber das script woni gschribe ha erstellt u füllt de ordner selber)

**Comment by timogi** [comment]
binarization muessme iz no mache

**Comment by RescueGum** [comment]
binarization with Otsu_binarization can now be applied after crop and resize.
drawback: most images the word now doesn't fill out the 100px box completely in the horizontal axis.
in my opinion this should be good enough.
